---
title: "Analysis Report -- Exp. weibull regression model"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  bookdown::html_document2:
    number_sections: no
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: hide
header-includes:
- \usepackage{graphicx}
- \usepackage{float}
editor_options:
  chunk_output_type: console
---

```{r setup knit, include=FALSE}
knitr::opts_chunk$set(
	fig.align = "center",
	fig.pos = "H",
	message = FALSE,
	warning = FALSE,
	external = TRUE,
	echo = TRUE
)

library(tidyverse)
library(data.table)
library(magrittr)
library(ggsci)
library(kableExtra)

source("./scripts/functions.R")

raw_data <- readxl::read_excel("./data/IS_data.xlsx") %>% clean_data(c("Day after spray","Deaths"))
```


## Age 14 {.tabset}

### Raw data

```{r control raw data plot}
raw_14 <- raw_data %>% filter(Age==14 & Treatment!="Control") %>% droplevels()
raw_14 %>% get_survival_percent() %>% plot_survival_percent() + facet_grid(~Sex)
```

### Model 

```{r control thin draws}
posterior_dist <- read.csv("./data/posterior_age14.csv") %>% burn_n_thin_draws(jump = 220, burn_at = 1)
# posterior_dist %>%
#   reshape2::melt() %>%
#   ggplot(aes(x = value)) +
#   geom_density() +
#   facet_wrap(~variable, scales = "free", ncol = 3)
apply(posterior_dist, 2, function(col) quantile(col, probs = c(0.025,0.5,0.975))) %>% 
  t() %>% 
  set_colnames(c("Lower","Estimate","Upper")) %>% 
  kable()
```

```{r control dummy columns}
dummy_14 <- 
  raw_14 %>% 
  mutate(intercept = 1,
         infected = ifelse(Treatment=="Infected", 1, 0),
         female = ifelse(Sex=="Female", 1, 0),
         aco = ifelse(Population == "ACO", 1, 0),
         inf_female = infected*female,
         inf_aco = infected*aco,
         female_aco = female*aco,
         inf_f_aco = infected*female*aco) %>% 
  select(Day,intercept,infected,female,aco,inf_female,inf_aco,female_aco,inf_f_aco)
```

```{r control survival function}
max_day <- 120
subgroups_14 <- dummy_14 %>% dplyr::select(-Day) %>% unique()

survival_14 <- 
  apply(subgroups_14, 1, function(row) survival_interval_calculator(posterior_dist, x_fit = row, max_day = max_day)) %>%
  data.frame() %>% 
  add_survival_initial(subgroups_14, max_day = max_day) %>% 
  rowwise() %>% 
  mutate(Treatment = ifelse(infected == 1, "Infected", "Uninfected"),
         Sex = ifelse(female == 1, "Female", "Male"),
         Population = ifelse(aco == 1, "ACO", "CO"),
         Age = 14) %>% 
  select(Treatment, Sex, Population, Age, Day, est, lower, upper)

survival_14 %>% plot_survival_function() + facet_grid(~Sex) + xlim(14,120)
```

```{r age 14 immunity}
aco_female = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_14 %>% filter(aco==1 & female==1 & infected==1), 
  s2 = subgroups_14 %>% filter(aco==1 & female==1 & infected==0)
) %>% mutate(tag = "ACO Female", Sex = "Female", Population = "ACO")

aco_male = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_14 %>% filter(aco==1 & female==0 & infected==1), 
  s2 = subgroups_14 %>% filter(aco==1 & female==0 & infected==0)
) %>% mutate(tag = "ACO Male", Sex = "Male", Population = "ACO")

co_female = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_14 %>% filter(aco==0 & female==1 & infected==1), 
  s2 = subgroups_14 %>% filter(aco==0 & female==1 & infected==0)
) %>% mutate(tag = "CO Female", Sex = "Female", Population = "CO")

co_male = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_14 %>% filter(aco==0 & female==0 & infected==1), 
  s2 = subgroups_14 %>% filter(aco==0 & female==0 & infected==0)
) %>% mutate(tag = "CO Male", Sex = "Male", Population = "CO")

age14_immunity = 
  rbind(aco_female,aco_male, co_female, co_male) %>% 
  set_colnames(c("lower","est","upper","tag","Sex","Population")) %>% 
  mutate(Age = "14")
```




## Age 28 {.tabset}

### Raw data

```{r control raw data plot}
raw_28 <- raw_data %>% filter(Age==28 & Treatment!="Control") %>% droplevels()
raw_28 %>% get_survival_percent() %>% plot_survival_percent() + facet_grid(~Sex)
```

### Model 

```{r control thin draws}
posterior_dist <- read.csv("./data/posterior_age28.csv") %>% burn_n_thin_draws(jump = 220, burn_at = 1)
# posterior_dist %>%
#   reshape2::melt() %>%
#   ggplot(aes(x = value)) +
#   geom_density() +
#   facet_wrap(~variable, scales = "free", ncol = 3)
apply(posterior_dist, 2, function(col) quantile(col, probs = c(0.025,0.5,0.975))) %>% 
  t() %>% 
  set_colnames(c("Lower","Estimate","Upper")) %>% 
  kable()
```

```{r control dummy columns}
dummy_28 <- 
  raw_28 %>% 
  mutate(intercept = 1,
         infected = ifelse(Treatment=="Infected", 1, 0),
         female = ifelse(Sex=="Female", 1, 0),
         aco = ifelse(Population == "ACO", 1, 0),
         inf_female = infected*female,
         inf_aco = infected*aco,
         female_aco = female*aco,
         inf_f_aco = infected*female*aco) %>% 
  select(Day,intercept,infected,female,aco,inf_female,inf_aco,female_aco,inf_f_aco)
```

```{r control survival function}
max_day <- 100
subgroups_28 <- dummy_28 %>% dplyr::select(-Day) %>% unique()

survival_28 <- 
  apply(subgroups_28, 1, function(row) survival_interval_calculator(posterior_dist, x_fit = row, max_day = max_day)) %>%
  data.frame() %>% 
  add_survival_initial(subgroups_28, max_day = max_day) %>% 
  rowwise() %>% 
  mutate(Treatment = ifelse(infected == 1, "Infected", "Uninfected"),
         Sex = ifelse(female == 1, "Female", "Male"),
         Population = ifelse(aco == 1, "ACO", "CO"),
         Age = 28) %>% 
  select(Treatment, Sex, Population, Age, Day, est, lower, upper)

survival_28 %>% plot_survival_function() + facet_grid(~Sex) + xlim(14,120)
```

```{r age 14 immunity}
aco_female = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_28 %>% filter(aco==1 & female==1 & infected==1), 
  s2 = subgroups_28 %>% filter(aco==1 & female==1 & infected==0)
) %>% mutate(tag = "ACO Female", Sex = "Female", Population = "ACO")

aco_male = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_28 %>% filter(aco==1 & female==0 & infected==1), 
  s2 = subgroups_28 %>% filter(aco==1 & female==0 & infected==0)
) %>% mutate(tag = "ACO Male", Sex = "Male", Population = "ACO")

co_female = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_28 %>% filter(aco==0 & female==1 & infected==1), 
  s2 = subgroups_28 %>% filter(aco==0 & female==1 & infected==0)
) %>% mutate(tag = "CO Female", Sex = "Female", Population = "CO")

co_male = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_28 %>% filter(aco==0 & female==0 & infected==1), 
  s2 = subgroups_28 %>% filter(aco==0 & female==0 & infected==0)
) %>% mutate(tag = "CO Male", Sex = "Male", Population = "CO")

age28_immunity = 
  rbind(aco_female,aco_male, co_female, co_male) %>% 
  set_colnames(c("lower","est","upper","tag","Sex","Population")) %>% 
  mutate(Age = "28")
```






## Age 42 {.tabset}

### Raw data

```{r }
raw_42 <- raw_data %>% filter(Age==42 & Treatment!="Control") %>% droplevels()
raw_42 %>% get_survival_percent() %>% plot_survival_percent() + facet_grid(~Sex)
```

### Model 

```{r}
posterior_dist <- read.csv("./data/posterior_age42.csv") %>% burn_n_thin_draws(jump = 220, burn_at = 1)
# posterior_dist %>%
#   reshape2::melt() %>%
#   ggplot(aes(x = value)) +
#   geom_density() +
#   facet_wrap(~variable, scales = "free", ncol = 3)
apply(posterior_dist, 2, function(col) quantile(col, probs = c(0.025,0.5,0.975))) %>% 
  t() %>% 
  set_colnames(c("Lower","Estimate","Upper")) %>% 
  kable()
```

```{r }
dummy_42 <- 
  raw_42 %>% 
  mutate(intercept = 1,
         infected = ifelse(Treatment=="Infected", 1, 0),
         female = ifelse(Sex=="Female", 1, 0),
         aco = ifelse(Population == "ACO", 1, 0),
         inf_female = infected*female,
         inf_aco = infected*aco,
         female_aco = female*aco,
         inf_f_aco = infected*female*aco) %>% 
  select(Day,intercept,infected,female,aco,inf_female,inf_aco,female_aco,inf_f_aco)
```

```{r }
max_day <- 100
subgroups_42 <- dummy_42 %>% dplyr::select(-Day) %>% unique()

survival_42 <- 
  apply(subgroups_42, 1, function(row) survival_interval_calculator(posterior_dist, x_fit = row, max_day = max_day)) %>%
  data.frame() %>% 
  add_survival_initial(subgroups_42, max_day = max_day) %>% 
  rowwise() %>% 
  mutate(Treatment = ifelse(infected == 1, "Infected", "Uninfected"),
         Sex = ifelse(female == 1, "Female", "Male"),
         Population = ifelse(aco == 1, "ACO", "CO"),
         Age = 42) %>% 
  select(Treatment, Sex, Population, Age, Day, est, lower, upper)

survival_42 %>% plot_survival_function() + facet_grid(~Sex) + xlim(14, 120)
```

```{r }
aco_female = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_42 %>% filter(aco==1 & female==1 & infected==1), 
  s2 = subgroups_42 %>% filter(aco==1 & female==1 & infected==0)
) %>% mutate(tag = "ACO Female", Sex = "Female", Population = "ACO")

aco_male = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_42 %>% filter(aco==1 & female==0 & infected==1), 
  s2 = subgroups_42 %>% filter(aco==1 & female==0 & infected==0)
) %>% mutate(tag = "ACO Male", Sex = "Male", Population = "ACO")

co_female = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_42 %>% filter(aco==0 & female==1 & infected==1), 
  s2 = subgroups_42 %>% filter(aco==0 & female==1 & infected==0)
) %>% mutate(tag = "CO Female", Sex = "Female", Population = "CO")

co_male = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_42 %>% filter(aco==0 & female==0 & infected==1), 
  s2 = subgroups_42 %>% filter(aco==0 & female==0 & infected==0)
) %>% mutate(tag = "CO Male", Sex = "Male", Population = "CO")

age42_immunity = 
  rbind(aco_female,aco_male, co_female, co_male) %>% 
  set_colnames(c("lower","est","upper","tag","Sex","Population")) %>% 
  mutate(Age = "42")
```










## Control vs Uninfected {.tabset}

### Raw data

```{r control raw data plot}
raw_control <- raw_data %>% filter(Age==14 & Treatment!="Infected") %>% droplevels()
raw_control %>% get_survival_percent() %>% plot_survival_percent() + facet_grid(~Sex)

raw_control %>%
  group_by(Population, Treatment, Sex,Day) %>% 
    summarise(Deaths = sum(Deaths)) %>% 
    group_by(Population, Treatment,Sex) %>% 
    mutate(Total = sum(Deaths),
           Deaths = cumsum(Deaths)) %>% 
    ungroup() %>% 
    mutate(Percent = 1 - Deaths/Total) %>% 
    select(-c(Total,Deaths)) %>% 
  ggplot(aes(x=Day, y=Percent, linetype = Sex,
             color = interaction(Treatment,Population),
             group = interaction(Treatment,Population,Sex))) +
  geom_line() +
  geom_point(size = 0.7)+
  facet_grid(~Sex)
```

### Model 

```{r control thin draws}
posterior_dist <- read.csv("data/posterior_control_2020-04-14.csv") %>% 
  burn_n_thin_draws(jump = 220, burn_at = 1)
# posterior_dist %>%
#   reshape2::melt() %>%
#   ggplot(aes(x = value)) +
#   geom_density() +
#   facet_wrap(~variable, scales = "free", ncol = 3)
apply(posterior_dist, 2, function(col) quantile(col, probs = c(0.025,0.5,0.975))) %>% 
  t() %>% 
  set_colnames(c("Lower","Estimate","Upper")) %>% 
  kable()
```

```{r control dummy columns}
dummy_control <- 
  raw_control %>% 
  mutate(intercept = 1,
         control = ifelse(Treatment=="Control", 1, 0),
         female = ifelse(Sex=="Female", 1, 0),
         aco = ifelse(Population == "ACO", 1, 0),
         control_female = control*female,
         control_aco = control*aco,
         female_aco = female*aco,
         control_f_aco = control*female*aco) %>% 
  select(Day,intercept,control,female,aco,control_female,control_aco,female_aco,control_f_aco)
```

```{r control survival function}
max_day <- 85
subgroups_control <- dummy_control %>% dplyr::select(-Day) %>% unique()

survival_control <- 
  apply(subgroups_control, 1, function(row) survival_interval_calculator(posterior_dist, x_fit = row, max_day = max_day)) %>%
  data.frame() %>% 
  add_survival_initial(subgroups_control, max_day = max_day) %>% 
  rowwise() %>% 
  mutate(Treatment = ifelse(control == 1, "Control", "Uninfected"),
         Sex = ifelse(female == 1, "Female", "Male"),
         Population = ifelse(aco == 1, "ACO", "CO"),
         Age = 14) %>% 
  select(Treatment, Sex, Population, Age, Day, est, lower, upper)

survival_control %>% plot_survival_function() + facet_grid(~Sex)


survival_control %>% 
  ggplot(aes(x=Day, y=est, linetype = Sex,
             color = interaction(Treatment,Population),
             group = interaction(Treatment,Population,Sex))) +
  geom_line()
```


```{r control hazard ratio}
aco_female = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_control %>% filter(aco==1 & female==1 & control==1), 
    s2 = subgroups_control %>% filter(aco==1 & female==1 & control==0)
) %>% as.data.frame() %>% mutate(tag = "ACO Female", Sex = "Female")

aco_male = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_control %>% filter(aco==1 & female==0 & control==1), 
    s2 = subgroups_control %>% filter(aco==1 & female==0 & control==0)
) %>% as.data.frame() %>% mutate(tag = "ACO Male", Sex = "Male")

co_female = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_control %>% filter(aco==0 & female==1 & control==1), 
    s2 = subgroups_control %>% filter(aco==0 & female==1 & control==0)
) %>% as.data.frame() %>% mutate(tag = "CO Female", Sex = "Female")

co_male = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_control %>% filter(aco==0 & female==0 & control==1), 
    s2 = subgroups_control %>% filter(aco==0 & female==0 & control==0)
) %>% as.data.frame() %>% mutate(tag = "CO Male", Sex = "Male")

cut_off = 10
rbind(
  aco_female[-c((nrow(aco_female)-cut_off):nrow(aco_female)),], 
  aco_male[-c((nrow(aco_male)-cut_off):nrow(aco_male)),],
  co_female[-c((nrow(co_female)-cut_off):nrow(co_female)),], 
  co_male[-c((nrow(co_male)-cut_off):nrow(co_male)),]
  ) %>% 
  plot_hazard_ratio() + 
  geom_hline(yintercept = 1, linetype = "dashed") +
  facet_grid(~Sex)
```

```{r control median residual life}
control_median_residual <-
  apply(
    subgroups_control, 1,
    function(row) median_residual_interval_calculator(posterior_dist, x_fit = row, max_day = max_day)) %>%
  data.frame() %>%
  add_median_residual_initial(subgroups_control, max_day = max_day) %>%
  rowwise() %>%
  mutate(Population = ifelse(aco == 1, "ACO", "CO"),
         Treatment = ifelse(control == 1, "Control", "Uninfected"),
         Sex = ifelse(female == 1, "Female", "Male"),
         Age = 14) %>%
  select(Treatment, Population, Sex, Age, Day, est, lower, upper) %>%
  filter(est >= 1)

control_median_residual %>% 
  ggplot(aes(x=Day, y=est, ymin=lower, ymax=upper, color=paste(Treatment,Sex))) +
  geom_line() +
  geom_errorbar() +
  facet_wrap(~Population, scales = "free_y")
```


## ACO {.tabset}

### Raw data

```{r aco raw data plot}
raw_aco <- raw_data %>% filter(Treatment!="Control" & Population=="ACO") %>% droplevels()
raw_aco %>% get_survival_percent() %>% plot_survival_percent2()
```

### Model

```{r aco thin draws}
posterior_dist <- read.csv("data/posterior_aco_2020-04-14.csv")[-1,] %>% burn_n_thin_draws(jump = 260, burn_at = 1)
# posterior_dist %>%
#   reshape2::melt() %>%
#   ggplot(aes(x = value)) +
#   geom_density() +
#   facet_wrap(~variable, scales = "free", ncol = 3)
apply(posterior_dist, 2, function(col) quantile(col, probs = c(0.025,0.5,0.975))) %>% 
  t() %>% 
  kable()
```

```{r aco dummy columns}
dummy_aco <- 
  raw_aco %>% 
  mutate(
    intercept = 1,
    infected = ifelse(Treatment == "Infected", 1, 0),
    female = ifelse(Sex == "Female", 1, 0),
    age_14 = ifelse(Age == 14, 1, 0),
    age_28 = ifelse(Age == 28, 1, 0),
    inf_female = infected*female, 
    inf_14 = infected*age_14,
    inf_28 = infected*age_28,
    female_14 = female*age_14,
    female_28 = female*age_28
    ) %>% 
    dplyr::select(c(Day, intercept, infected, female, age_14, age_28, inf_female, inf_14, inf_28, female_14, female_28))
```


```{r aco survival function}
max_day <- 46
subgroups_aco <- dummy_aco %>% dplyr::select(-Day) %>% unique()

survival_aco <- 
  apply(subgroups_aco, 1, function(row) survival_interval_calculator(posterior_dist, x_fit = row, max_day = max_day)) %>%
  data.frame() %>% 
  add_survival_initial(subgroups_aco, max_day = max_day) %>% 
  rowwise() %>% 
  mutate(Treatment = ifelse(infected == 1, "Infected", "Uninfected"),
         Sex = ifelse(female == 1, "Female", "Male"),
         Age = convert_age_back(age_14, age_28),
         Population = "ACO") %>% 
  select(Treatment, Sex, Age, Population, Day, est, lower, upper)

survival_aco %>% plot_survival_function2()
# survival_aco %>% plot_survival_function2() + facet_grid(~paste("Age",Age))
```


```{r aco Sex hazard ratio}
unf_14 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_aco %>% filter(infected==0 & age_14==1 & female==1), 
    s2 = subgroups_aco %>% filter(infected==0 & age_14==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Uninfected 14", Age = 14, Treatment = "Uninfected")

inf_14 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_aco %>% filter(infected==1 & age_14==1 & female==1), 
    s2 = subgroups_aco %>% filter(infected==1 & age_14==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Infected 14", Age = 14, Treatment = "Infected")

unf_28 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_aco %>% filter(infected==0 & age_28==1 & female==1), 
    s2 = subgroups_aco %>% filter(infected==0 & age_28==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Uninfected 28", Age = 28, Treatment = "Uninfected")

inf_28 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_aco %>% filter(infected==1 & age_28==1 & female==1), 
    s2 = subgroups_aco %>% filter(infected==1 & age_28==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Infected 28", Age = 28, Treatment = "Infected")

unf_42 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_aco %>% filter(infected==0 & age_14==0 & age_28==0 & female==1), 
    s2 = subgroups_aco %>% filter(infected==0 & age_14==0 & age_28==0 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Uninfected 42", Age = 42, Treatment = "Uninfected")

inf_42 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_aco %>% filter(infected==1 & age_14==0 & age_28==0 & female==1), 
    s2 = subgroups_aco %>% filter(infected==1 & age_14==0 & age_28==0 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Infected 42", Age = 42, Treatment = "Infected")


cut_off = 6
rbind(
  unf_14[-c((nrow(unf_14)-cut_off):nrow(unf_14)),], 
  inf_14[-c((nrow(inf_14)-cut_off):nrow(inf_14)),], 
  unf_28[-c((nrow(unf_28)-cut_off):nrow(unf_28)),], 
  inf_28[-c((nrow(inf_28)-cut_off):nrow(inf_28)),], 
  unf_42[-c((nrow(unf_42)-cut_off):nrow(unf_42)),], 
  inf_42[-c((nrow(inf_42)-cut_off):nrow(inf_42)),]
  ) %>% 
  ggplot(aes(x = Day, y = est, color = Treatment, ymin = lower, ymax = upper)) +
  geom_line(size = 1.2) +
  geom_errorbar(size = 0.7, alpha = 0.5) +
  facet_grid(Treatment~paste("Age", Age)) +
  geom_hline(yintercept = 1, linetype ="dashed") +
  labs(x = "Days after spray", y = "Hazard ratio", color = "", subtitle = "Baseline: male") +
  theme_minimal()
```

```{r aco infection hazard ratio}
# female_14 = 
#   hazard_ratio_calculator(
#     data = posterior_dist, max_day = max_day,
#     s1 = subgroups_aco %>% filter(female==1 & age_14==1 & infected==1), 
#     s2 = subgroups_aco %>% filter(female==1 & age_14==1 & infected==0)
# ) %>% as.data.frame() %>% mutate(tag = "Female 14", Age = 14, Sex = "Female")
# male_14 = 
#   hazard_ratio_calculator(
#     data = posterior_dist, max_day = max_day,
#     s1 = subgroups_aco %>% filter(female==0 & age_14==1 & infected==1), 
#     s2 = subgroups_aco %>% filter(female==0 & age_14==1 & infected==0)
# ) %>% as.data.frame() %>% mutate(tag = "Female 14", Age = 14, Sex = "Male")
# 
# female_28 = 
#   hazard_ratio_calculator(
#     data = posterior_dist, max_day = max_day,
#     s1 = subgroups_aco %>% filter(female==1 & age_28==1 & infected==1), 
#     s2 = subgroups_aco %>% filter(female==1 & age_28==1 & infected==0)
# ) %>% as.data.frame() %>% mutate(tag = "Female 28", Age = 28, Sex = "Female")
# male_28 = 
#   hazard_ratio_calculator(
#     data = posterior_dist, max_day = max_day,
#     s1 = subgroups_aco %>% filter(female==0 & age_28==1 & infected==1), 
#     s2 = subgroups_aco %>% filter(female==0 & age_28==1 & infected==0)
# ) %>% as.data.frame() %>% mutate(tag = "Female 28", Age = 28, Sex = "Male")
# 
# female_42 = 
#   hazard_ratio_calculator(
#     data = posterior_dist, max_day = max_day,
#     s1 = subgroups_aco %>% filter(female==1 & (age_14+age_28)==0 & infected==1), 
#     s2 = subgroups_aco %>% filter(female==1 & (age_14+age_28)==0 & infected==0)
# ) %>% as.data.frame() %>% mutate(tag = "Female 42", Age = 42, Sex = "Female")
# male_42 = 
#   hazard_ratio_calculator(
#     data = posterior_dist, max_day = max_day,
#     s1 = subgroups_aco %>% filter(female==0 & (age_14+age_28)==0 & infected==1), 
#     s2 = subgroups_aco %>% filter(female==0 & (age_14+age_28)==0 & infected==0)
# ) %>% as.data.frame() %>% mutate(tag = "Female 42", Age = 42, Sex = "Male")
# 
# cut_off = 6
# rbind(
#   female_14, male_14, female_28, male_28, female_42, male_42
#   ) %>% 
#   ggplot(aes(x = Day, y = est, color = Sex, ymin = lower, ymax = upper)) +
#   geom_line(size = 1.2) +
#   geom_errorbar(size = 0.7, alpha = 0.5) +
#   facet_wrap(~paste("Age", Age)) +
#   geom_hline(yintercept = 1, linetype ="dashed") +
#   labs(x = "Days after spray", y = "Hazard ratio", color = "", subtitle = "Baseline: Uninfected") +
#   theme_minimal()
```


```{r aco median residual life}
aco_median_residual <-
  apply(
    aco_subgroups, 1,
    function(row) median_residual_interval_calculator(posterior_dist, x_fit = row, max_day = max_day)) %>%
  data.frame() %>%
  add_median_residual_initial(aco_subgroups, max_day = max_day) %>%
  rowwise() %>%
  mutate(Treatment = ifelse(infected == 1, "Infected", "Uninfected"),
         Sex = ifelse(female == 1, "Female", "Male"),
         Age = convert_age_back(age_14, age_28)) %>%
  select(Treatment, Sex, Age, Day, est, lower, upper) %>%
  filter(est >= 1)

aco_median_residual %>% filter(Treatment == "Uninfected") %>% plot_median_residual(type = 2)
aco_median_residual %>% filter(Treatment == "Infected") %>% plot_median_residual(type = 2)
```

```{r aco median residual slope}
# aco_median_slope <-
#   aco_median_residual %>%
#   group_by(Treatment,Age,Sex) %>%
#   mutate(est = c(NA,diff(est)),
#          lower = c(NA,diff(lower)),
#          upper = c(NA,diff(upper))) %>%
#   na.omit()
# 
# aco_median_slope %>% filter(Treatment == "Uninfected") %>% plot_median_residual_slope(type = 1)
# aco_median_slope %>% filter(Treatment == "Infected") %>% plot_median_residual_slope(type = 1)
```


```{r aco immunity}
# aco age 14 female 
female_14 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_aco %>% filter(age_14==1 & female==1 & infected==1),
  s2 = subgroups_aco %>% filter(age_14==1 & female==1 & infected==0)
) %>% mutate(tag = "Female 14", Age = 14, Sex = "Female")
# aco age 14 male
male_14 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_aco %>% filter(age_14==1 & female==0 & infected==1),
  s2 = subgroups_aco %>% filter(age_14==1 & female==0 & infected==0)
) %>% mutate(tag = "Male 14", Age = 14, Sex = "Male")
# aco age 28 female 
female_28 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_aco %>% filter(age_28==1 & female==1 & infected==1),
  s2 = subgroups_aco %>% filter(age_28==1 & female==1 & infected==0)
) %>% mutate(tag = "Female 28", Age = 28, Sex = "Female")
# aco age 28 male
male_28 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_aco %>% filter(age_28==1 & female==0 & infected==1),
  s2 = subgroups_aco %>% filter(age_28==1 & female==0 & infected==0)
) %>% mutate(tag = "Male 28", Age = 28, Sex = "Male")
# aco age 42 female 
female_42 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_aco %>% filter((age_14+age_28)==0 & female==1 & infected==1),
  s2 = subgroups_aco %>% filter((age_14+age_28)==0 & female==1 & infected==0)
) %>% mutate(tag = "Female 42", Age = 42, Sex = "Female")
# aco age 42 male
female_42 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_aco %>% filter((age_14+age_28)==0 & female==0 & infected==1),
  s2 = subgroups_aco %>% filter((age_14+age_28)==0 & female==0 & infected==0)
) %>% mutate(tag = "Male 42", Age = 42, Sex = "Female")

aco_immunity = 
  rbind(female_14, female_28, female_42, male_14, male_28, male_42) %>% 
  set_colnames(c("lower","est","upper","tag","Age","Sex")) %>% 
  mutate(Population = "ACO")
```



## CO {.tabset}

### Raw data

```{r co raw data plot}
raw_co <- raw_data %>% filter(Treatment!="Control" & Population=="CO") %>% droplevels()
raw_co %>% get_survival_percent() %>% plot_survival_percent2() + facet_grid(~Sex)
```

### Model

```{r co thin draws}
# posterior_dist <- read.csv("./data/posterior_co_trials_recent_run.csv") %>% burn_n_thin_draws(jump = 350, burn_at = 1)
  posterior_dist <- read.csv("./data/posterior_co.csv")[-1,] %>% burn_n_thin_draws(jump = 350, burn_at = 1)
# posterior_dist %>%
#   reshape2::melt() %>%
#   ggplot(aes(x = value)) +
#   geom_density() +
#   facet_wrap(~variable, scales = "free", ncol = 4)
apply(posterior_dist, 2, function(col) quantile(col, probs = c(0.025,0.5,0.975))) %>% 
  t() %>% 
  kable()
```

```{r co dummy columns}
dummy_co <- 
  raw_co %>% 
  mutate(
      intercept = 1,
      infected = ifelse(Treatment == "Infected", 1, 0),
      female = ifelse(Sex == "Female", 1, 0),
      age_14 = ifelse(Age == 14, 1, 0),
      age_28 = ifelse(Age == 28, 1, 0),
      age_42 = ifelse(Age == 42, 1, 0),
      age_56 = ifelse(Age == 56, 1, 0),
      inf_female = infected*female, 
      inf_14 = infected*age_14,
      inf_28 = infected*age_28,
      inf_42 = infected*age_42,
      inf_56 = infected*age_56,
      female_14 = female*age_14,
      female_28 = female*age_28,
      female_42 = female*age_42,
      female_56 = female*age_56, 
      female_inf_14 = female*infected*age_14,
      female_inf_28 = female*infected*age_28,
      female_inf_42 = female*infected*age_42,
      female_inf_56 = female*infected*age_56
    ) %>% 
    dplyr::select(c(Day, intercept, infected, female, age_14, age_28, age_42, age_56,
                    inf_female, inf_14, inf_28, inf_42, inf_56, female_14, female_28, female_42, female_56,
                    female_inf_14, female_inf_28, female_inf_42, female_inf_56))
```


```{r co survival function}
max_day <- 120
subgroups_co <- dummy_co %>% dplyr::select(-Day) %>% unique()

survival_co <- 
  apply(subgroups_co, 1, function(row) survival_interval_calculator(posterior_dist, x_fit = row, max_day = max_day)) %>%
  data.frame() %>% 
  add_survival_initial(subgroups_co, max_day = max_day) %>% 
  rowwise() %>% 
  mutate(Treatment = ifelse(infected == 1, "Infected", "Uninfected"),
         Sex = ifelse(female == 1, "Female", "Male"),
         Age = convert_age_back2(age_14, age_28, age_42, age_56),
         Population = "CO") %>% 
  select(Treatment, Sex, Age, Population, Day, est, lower, upper)

survival_co %>% plot_survival_function2() + facet_grid(~Sex)
survival_co %>% plot_survival_function2() + facet_grid(~paste("Age",Age))
```



```{r co hazard ratio}
unf_14 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_co %>% filter(infected==0 & age_14==1 & female==1), 
    s2 = subgroups_co %>% filter(infected==0 & age_14==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Uninfected 14", Age = 14, Treatment = "Uninfected ")

inf_14 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_co %>% filter(infected==1 & age_14==1 & female==1), 
    s2 = subgroups_co %>% filter(infected==1 & age_14==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Infected 14", Age = 14, Treatment = "Infected ")

unf_28 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_co %>% filter(infected==0 & age_28==1 & female==1), 
    s2 = subgroups_co %>% filter(infected==0 & age_28==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Uninfected 28", Age = 28, Treatment = "Uninfected ")

inf_28 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_co %>% filter(infected==1 & age_28==1 & female==1), 
    s2 = subgroups_co %>% filter(infected==1 & age_28==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Infected 28", Age = 28, Treatment = "Infected ")

unf_42 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_co %>% filter(infected==0 & age_42==1 & female==1), 
    s2 = subgroups_co %>% filter(infected==0 & age_42==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Uninfected 42", Age = 42, Treatment = "Uninfected ")

inf_42 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_co %>% filter(infected==1 & age_42==1 & female==1), 
    s2 = subgroups_co %>% filter(infected==1 & age_42==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Infected 42", Age = 42, Treatment = "Infected ")

unf_56 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_co %>% filter(infected==0 & age_56==1 & female==1), 
    s2 = subgroups_co %>% filter(infected==0 & age_56==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Uninfected 56", Age = 56, Treatment = "Uninfected ")

inf_56 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_co %>% filter(infected==1 & age_56==1 & female==1), 
    s2 = subgroups_co %>% filter(infected==1 & age_56==1 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Infected 56", Age = 56, Treatment = "Infected ")

unf_70 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_co %>% filter(infected==0 & (age_14+age_28+age_42+age_56)==0 & female==1), 
    s2 = subgroups_co %>% filter(infected==0 & (age_14+age_28+age_42+age_56)==0 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Uninfected 70", Age = 70, Treatment = "Uninfected ")

inf_70 = 
  hazard_ratio_calculator(
    data = posterior_dist, max_day = max_day,
    s1 = subgroups_co %>% filter(infected==1 & (age_14+age_28+age_42+age_56)==0 & female==1), 
    s2 = subgroups_co %>% filter(infected==1 & (age_14+age_28+age_42+age_56)==0 & female==0)
) %>% as.data.frame() %>% mutate(tag = "Infected 70", Age = 70, Treatment = "Infected ")

cut_off = 30
rbind(
  unf_14[-c((nrow(unf_14)-cut_off):nrow(unf_14)),], 
  inf_14[-c((nrow(inf_14)-cut_off):nrow(inf_14)),], 
  unf_28[-c((nrow(unf_28)-cut_off):nrow(unf_28)),], 
  inf_28[-c((nrow(inf_28)-cut_off):nrow(inf_28)),], 
  unf_42[-c((nrow(unf_42)-cut_off):nrow(unf_42)),], 
  inf_42[-c((nrow(inf_42)-cut_off):nrow(inf_42)),],
  unf_56[-c((nrow(unf_56)-cut_off):nrow(unf_56)),], 
  inf_56[-c((nrow(inf_56)-cut_off):nrow(inf_56)),],
  unf_70[-c((nrow(unf_70)-cut_off):nrow(unf_70)),], 
  inf_70[-c((nrow(inf_70)-cut_off):nrow(inf_70)),]
  ) %>% 
  ggplot(aes(x = Day, y = est, color = Treatment, ymin = lower, ymax = upper, group = tag)) +
  geom_line(size = 1.2) +
  geom_errorbar(size = 0.7, alpha = 0.2) +
  facet_wrap(Treatment~paste("Age", Age), nrow = 2) +
  geom_hline(yintercept = 1, linetype ="dashed") +
  labs(x = "Days after spray", y = "Hazard ratio", color = "") +
  theme_minimal()
```

```{r co median residual life}
co_median_residual <-
  apply(
    co_subgroups, 1,
    function(row) median_residual_interval_calculator(posterior_dist, x_fit = row, max_day = max_day)) %>%
  data.frame() %>%
  add_median_residual_initial(co_subgroups, max_day = max_day) %>%
  rowwise() %>%
  mutate(Treatment = ifelse(infected == 1, "Infected", "Uninfected"),
         Sex = ifelse(female == 1, "Female", "Male"),
         Age = convert_age_back2(age_14, age_28, age_42, age_56)) %>%
  select(Treatment, Sex, Age, Day, est, lower, upper) %>%
  filter(est >= 1)

co_median_residual %>% filter(Treatment == "Uninfected") %>% plot_median_residual(type = 2)
co_median_residual %>% filter(Treatment == "Infected") %>% plot_median_residual(type = 2)
```

```{r co immunity}
# co age 14 female 
female_14 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_co %>% filter(age_14==1 & female==1 & infected==1),
  s2 = subgroups_co %>% filter(age_14==1 & female==1 & infected==0)
) %>% mutate(tag = "Female 14", Age = 14, Sex = "Female")

# co age 14 male
male_14 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_co %>% filter(age_14==1 & female==0 & infected==1),
  s2 = subgroups_co %>% filter(age_14==1 & female==0 & infected==0)
) %>% mutate(tag = "Male 14", Age = 14, Sex = "Male")

# co age 28 female 
female_28 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_co %>% filter(age_28==1 & female==1 & infected==1),
  s2 = subgroups_co %>% filter(age_28==1 & female==1 & infected==0)
) %>% mutate(tag = "Female 28", Age = 28, Sex = "Female")

# co age 28 male
male_28 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_co %>% filter(age_28==1 & female==0 & infected==1),
  s2 = subgroups_co %>% filter(age_28==1 & female==0 & infected==0)
) %>% mutate(tag = "Male 28", Age = 28, Sex = "Male")

# co age 42 female 
female_42 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_co %>% filter(age_42==1 & female==1 & infected==1),
  s2 = subgroups_co %>% filter(age_42==1 & female==1 & infected==0)
) %>% as.data.frame() %>% mutate(tag = "Female 42", Age = 42, Sex = "Female")

# co age 42 male
male_42 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_co %>% filter(age_42==1 & female==0 & infected==1),
  s2 = subgroups_co %>% filter(age_42==1 & female==0 & infected==0)
) %>% as.data.frame() %>% mutate(tag = "Male 42", Age = 42, Sex = "Male")

# co age 56 female 
female_56 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_co %>% filter(age_56==1 & female==1 & infected==1),
  s2 = subgroups_co %>% filter(age_56==1 & female==1 & infected==0)
) %>% mutate(tag = "Female 56", Age = 56, Sex = "Female")

# co age 56 male
male_56 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_co %>% filter(age_56==1 & female==0 & infected==1),
  s2 = subgroups_co %>% filter(age_56==1 & female==0 & infected==0)
) %>% mutate(tag = "Male 56", Age = 56, Sex = "Male")

# co age 70 female 
female_70 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_co %>% filter((age_14+age_28+age_42+age_56)==0 & female==1 & infected==1),
  s2 = subgroups_co %>% filter((age_14+age_28+age_42+age_56)==0 & female==1 & infected==0)
) %>% mutate(tag = "Female 70", Age = 70, Sex = "Female")

# co age 70 male
male_70 = get_change_on_sigma(
  data = posterior_dist,
  s1 = subgroups_co %>% filter((age_14+age_28+age_42+age_56)==0 & female==0 & infected==1),
  s2 = subgroups_co %>% filter((age_14+age_28+age_42+age_56)==0 & female==0 & infected==0)
) %>% mutate(tag = "Male 70", Age = 70, Sex = "Male")

co_immunity = 
  rbind(female_14, female_28, female_42, female_56, female_70,
      male_14, male_28, male_42, male_56, male_70) %>% 
  set_colnames(c("lower","est","upper","tag","Age","Sex")) %>% 
  mutate(Population = "CO")

immunity = rbind(aco_immunity, co_immunity)

immunity %>% 
  filter(Population=="ACO") %>% 
  ggplot(aes(x=Age, y=est, ymin=lower, ymax=upper, color=Sex)) +
  geom_errorbar(width = 1,alpha=0.7) +
  geom_point() +
  theme_minimal() +
  labs(x = "Age", y = "Immunity Measurement", color = "")
```






